bitbucket: # BitBucket access settings
  login: login # user name, not e-mail, see https://bitbucket.org/account/settings/
  password: password # app password with account, repositories and issues read permission, see https://bitbucket.org/account/settings/app-passwords/
  owner: owner # repositories owner
issues: # issues loading settings
  repositoriesFilter: # repositories filter, see https://developer.atlassian.com/cloud/bitbucket/rest/intro/#filtering
  issuesFilter: (state = "new" OR state = "open" OR state = "on hold") AND (priority = "major" OR priority = "critical" OR priority = "blocker") # issues filter
storage: # cache storage settings
  dsn: memory:// # memory:// and redis:// supported
  ttl: PT6H # cache duration, ISO 8601
