bitbucket:
  login: login
  password: password
  owner: owner
issues:
  ttl: P6H
  repositoriesFilter:
  issuesFilter: (state = "new" OR state = "open" OR state = "on hold") AND (priority = "major" OR priority = "critical" OR priority = "blocker")
