bitbucket:
  login: login
  password: password
  owner: owner
issues:
  repositoriesFilter:
  issuesFilter: (state = "new" OR state = "open" OR state = "on hold") AND (priority = "major" OR priority = "critical" OR priority = "blocker")
storage:
  dsn: redis://localhost:6379/0
  ttl: PT6H
