name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        working-directory: deployments/docker-swarm-terraform
        run: terraform init

      # - name: Deploy Docker service to Swarm
      #   working-directory: deployments/docker-swarm-terraform
      #   run: |
      #     eval "$(ssh-agent -s)"
      #     ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
      #     terraform plan -input=false -var 'swarm-manager-host=${{ secrets.SWARM_MANAGER_HOST }}' -var 'app-name=${{ vars.APP_NAME }}' -var 'app-host=${{ secrets.APP_HOST }}' -var 'app-auth=${{ secrets.APP_AUTH }}' -var 'app-config-b64=${{ secrets.APP_CONFIG_B64 }}'

      - name: Deploy Docker service to Swarm
        working-directory: deployments/docker-swarm-terraform
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          terraform apply -auto-approve -input=false -var 'swarm-manager-host=${{ secrets.SWARM_MANAGER_HOST }}' -var 'app-name=${{ vars.APP_NAME }}' -var 'app-host=${{ secrets.APP_HOST }}' -var 'app-auth=${{ secrets.APP_AUTH }}' -var 'app-config-b64=${{ secrets.APP_CONFIG_B64 }}' -var "app-version=${GITHUB_REF#refs/tags/v}"
